/**
 * Generates `fixtures/journey/live-activity-signals-v1.json`: for every
 * generated session payload (`fixtures/journey/session-views-v1.json`), the
 * ride signal, moment and milestone the server's Live Activity push would
 * carry (`services/api/src/liveActivityContent.ts`). The Swift core recomputes
 * each with `LiveSessionInterpreter.rideSignal` and `RideGuidancePolicy` and
 * must agree (`LiveSessionInterpreterTests`), so a push can never say what the
 * app would not.
 *
 *   node --experimental-strip-types scripts/journey/live-activity-signals.ts [--check]
 *
 * SYNTHETIC: derived from synthetic payloads. No network.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { JourneySessionView } from "../../services/api/src/journeySession.ts";
import { rideMilestone, rideMoment, rideSignalFromSession } from "../../services/api/src/liveActivityContent.ts";

const views = JSON.parse(readFileSync(path.resolve("fixtures/journey/session-views-v1.json"), "utf8")) as {
  scenarios: Array<{ id: string; view: JourneySessionView }>;
};
const signals = views.scenarios.map(({ id, view }) => {
  const signal = rideSignalFromSession(view);
  const moment = rideMoment(signal);
  const milestone = rideMilestone(moment);
  return { id, signal, moment, ...(milestone ? { milestone } : {}) };
});

const out = path.resolve("fixtures/journey/live-activity-signals-v1.json");
const text = `${JSON.stringify({
  "//": "SYNTHETIC. Generated by scripts/journey/live-activity-signals.ts from session-views-v1.json with the server's Live Activity port (services/api/src/liveActivityContent.ts). The Swift core must compute the same signal, moment and milestone for each scenario.",
  signals,
}, null, 2)}\n`;

if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== text) {
    console.error("fixtures/journey/live-activity-signals-v1.json is out of date; run scripts/journey/live-activity-signals.ts");
    process.exit(1);
  }
  console.log(`live activity signals current (${signals.length} scenarios)`);
} else {
  writeFileSync(out, text);
  console.log(`wrote ${path.relative(process.cwd(), out)} (${signals.length} scenarios)`);
}
