/**
 * Product copy the website quotes from the iOS app.
 *
 * Every value here is copied verbatim from
 * `apps/ios/Resources/ko.lproj/Localizable.strings` under the same key, and
 * `test/rideCopy.test.ts` fails when the two drift. The website demonstrates
 * the native product; it must not invent its own wording for the same moment.
 */

export const IOS_COPY = {
  "home.question": "어디서 내릴까요?",
  "home.search.placeholder": "내릴 정류장 검색",
  "home.privacy": "탑서는 버스를 따라가요. 내 위치 권한은 필요 없어요.",
  "demo.chip": "체험판 · 합성 데이터",
  "home.recentDestinations": "최근 내린 곳",
  "home.recentJourney": "최근 여정",
  "home.rideAgain": "다시 타기",
  "favorite.from": "%@에서 타요",
  "home.mapImport.title": "지도 앱에서 가져오기",
  "home.mapImport.body": "스크린샷이나 공유한 장소로 시작",
  "search.results": "정류장",
  "route.question": "어떤 버스를 탈까요?",
  "route.headsign": "%@ 방면",
  "route.boardingCount": "%ld곳에서 탈 수 있어요",
  "boarding.question": "어디서 타나요?",
  "boarding.explain": "버스를 타는 정류장만 알려주세요. 여정 전체의 출발지는 필요 없어요.",
  "boarding.stopsToDestination": "내릴 곳까지 %ld정거장",
  "recap.getOffAt": "내릴 곳",
  "check.searching.headline": "버스를 찾고 있어요",
  "check.searching.detail": "정류장으로 오는 %@번을 확인하고 있어요",
  "check.proposed.headline": "이 버스로 보여요",
  "check.proposed.detail": "탈 때 번호판 끝자리를 확인해주세요",
  "check.similarBuses.headline": "비슷한 버스가 있어요",
  "check.similarBuses.detail": "탑승한 버스를 골라주세요",
  "check.confirmed.headline": "버스를 확인했어요",
  "check.confirmed.detail": "체험판은 앱을 켜 두면 끝까지 진행돼요",
  "check.confirm": "맞아요, 이 버스를 탔어요",
  "check.reject": "다른 버스예요",
  "check.noneOfThese": "둘 다 아니에요",
  "check.plateHint": "버스 번호판 끝자리",
  "check.position.atStop": "정류장에 도착",
  "check.position.away": "%ld정거장 전",
  "check.why":
    "탑서는 확실하지 않으면 버스를 대신 고르지 않아요. 한 번만 확인해주시면 그다음은 탑서가 지켜볼게요.",
  "ride.riding.eyebrow": "타고 가는 중",
  "ride.riding.headline": "내릴 때 알려드릴게요",
  "ride.riding.detail": "지금은 편하게 가셔도 돼요",
  "ride.prepare.eyebrow": "내릴 준비",
  "ride.prepare.headline": "2정거장 남았어요",
  "ride.prepare.detail": "내릴 준비를 해주세요",
  "ride.prepare.compact": "준비",
  "ride.nextStop.eyebrow": "다음 정류장",
  "ride.nextStop.headline": "다음에 내려요",
  "ride.nextStop.detail": "다음 정류장이 목적지예요. 하차벨을 눌러주세요",
  "ride.nextStop.compact": "다음 하차",
  "ride.arrived.eyebrow": "도착",
  "ride.arrived.headline": "여기서 내려요",
  "ride.arrived.detail": "목적지에 도착했어요",
  "ride.arrived.compact": "내려요",
  "ride.passedDestination.eyebrow": "목적지 지남",
  "ride.passedDestination.headline": "목적지를 지났어요",
  "ride.passedDestination.detail": "다음 정류장에서 내려 돌아가세요",
  "ride.passedDestination.compact": "지났어요",
  "ride.delayed.eyebrow": "위치 확인 필요",
  "ride.delayed.headline": "현재 위치를 정확히 확인하기 어려워요",
  "ride.delayed.detail": "차내 안내방송과 정류장 표시를 함께 확인해주세요.",
  "ride.delayed.compact": "위치 확인",
  "ride.vehicleLost.eyebrow": "위치 확인 필요",
  "ride.vehicleLost.headline": "현재 위치를 정확히 확인하기 어려워요",
  "ride.vehicleLost.detail": "차내 안내방송과 정류장 표시를 함께 확인해주세요.",
  "ride.vehicleLost.compact": "위치 확인",
  "ride.offline.eyebrow": "위치 확인 필요",
  "ride.offline.headline": "현재 위치를 정확히 확인하기 어려워요",
  "ride.offline.detail": "차내 안내방송과 정류장 표시를 함께 확인해주세요.",
  "ride.offline.compact": "위치 확인",
  "ride.checking.eyebrow": "위치 확인 필요",
  "ride.checking.headline": "현재 위치를 정확히 확인하기 어려워요",
  "ride.checking.detail": "차내 안내방송과 정류장 표시를 함께 확인해주세요.",
  "ride.checking.compact": "위치 확인",
  "ride.toDestination": "%@까지",
  "ride.nextStopLabel": "다음 정류장",
  "ride.now": "지금",
  "ride.getOffHere": "내릴 곳",
  "ride.gotOff": "내렸어요",
  "ride.closeApp": "체험판은 앱을 켜 둔 동안 진행돼요. 잠금 화면과 다이나믹 아일랜드에도 같은 안내가 보여요.",
  "ride.end": "여정 끝내기",
  "count.unit": "정거장",
  "count.unit.long": "정거장 남았어요",
  "count.lastKnown": "마지막 확인",
  "trust.vehicle.confirmed": "차량 확인됨",
  "trust.vehicle.rechecking": "차량 확인 중",
  "trust.vehicle.lost": "버스 찾는 중",
  "trust.data.live": "실시간",
  "trust.data.delayed": "업데이트 지연",
  "trust.data.offline": "오프라인",
  "trust.data.checking": "연결 확인 중",
  "alert.prepare.title": "2정거장 남았어요",
  "alert.prepare.body": "내릴 준비를 해주세요",
  "alert.nextStop.title": "다음에 내려요",
  "alert.arrived.title": "여기서 내려요",
  "handoff.naver.findDestination": "네이버 지도에서 목적지 찾기",
  "a11y.island.hint": "길게 눌러 여정 자세히 보기",
} as const;

export type CopyKey = keyof typeof IOS_COPY;

/** Fills `%@` / `%ld` placeholders in order, the way `String(format:)` does. */
export function t(key: CopyKey, ...args: Array<string | number>): string {
  let index = 0;
  return IOS_COPY[key].replace(/%(@|ld)/g, () => String(args[index++] ?? ""));
}
