/**
 * Ground-truth journey sessions, summarised: what the session coordinator in
 * automatic mode selects when the answer is known, and whether it withdraws a
 * selection the feed then shows to be wrong (finding F20).
 *
 *   node --experimental-strip-types scripts/matcher-evidence/ground-truth-sessions.ts \
 *     [--sessions=3000] [--out=artifacts/matcher-directed-v1/ground-truth-sessions.json]
 *
 * Label: SIMULATED. Every session is generated by
 * `services/api/test/groundTruthKit.ts`: buses move continuously at 20–90 s per
 * stop, the feed shows each only while it is visible, and the rider boards the
 * first bus to reach the stop. The truth is computed there and never reaches
 * the coordinator. Nothing here is an observation, and nothing here is release
 * gate evidence. The same code always writes the same file.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { MATCHER_POLICY_VERSION } from "../../services/api/src/matching.ts";
import {
  firstShownReaching,
  generateGroundTruthSession,
  runGroundTruthSession,
} from "../../services/api/test/groundTruthKit.ts";

const options = new Map(process.argv.slice(2).map((arg) => {
  const [key, ...value] = arg.replace(/^--/, "").split("=");
  return [key!, value.join("=")];
}));
const sessions = Number(options.get("sessions") || 3_000);
if (!Number.isSafeInteger(sessions) || sessions < 1) {
  console.error("--sessions must be a positive integer");
  process.exit(2);
}
const outPath = path.resolve(options.get("out") || "artifacts/matcher-directed-v1/ground-truth-sessions.json");

const counts = {
  sessions: 0,
  /** Sessions in which the coordinator selected a bus on its own. */
  automaticSelections: 0,
  /** The selected bus is the one the rider boards. */
  right: 0,
  /** Another bus; the boarded one had been in the feed before the selection. */
  wrongBoardedBusSeen: 0,
  /** Another bus; the boarded one had never been in the feed before the selection. */
  wrongBoardedBusNeverSeen: 0,
  /** No bus reaches the stop within the session, so no answer to score against. */
  noArrival: 0,
  wrongWithdrawn: 0,
  wrongNotWithdrawn: 0,
  /** Right selections withdrawn all the same: the cost of the watch. */
  rightWithdrawn: 0,
  /** Wrong selections where the feed showed the boarded bus reaching the stop no later than the selected one (P16). */
  shownOvertaken: 0,
  /** Of those, not withdrawn by that poll. P16 requires zero. */
  shownOvertakenNotWithdrawn: 0,
};

for (let seed = 1; seed <= sessions; seed += 1) {
  const session = generateGroundTruthSession(seed);
  const run = await runGroundTruthSession(session);
  counts.sessions += 1;
  if (!run.selected) continue;
  counts.automaticSelections += 1;
  const boarded = session.truth?.bus;
  if (!boarded) {
    counts.noArrival += 1;
    continue;
  }
  const withdrawn = run.withdrawnAt !== undefined;
  if (boarded.id === run.selected.vehicleId) {
    counts.right += 1;
    if (withdrawn) counts.rightWithdrawn += 1;
    continue;
  }
  const seenBefore = session.polls.some((poll) => poll.t <= run.selected!.at && poll.vehicles.some((row) => row.vehicleId === boarded.id));
  if (seenBefore) counts.wrongBoardedBusSeen += 1; else counts.wrongBoardedBusNeverSeen += 1;
  if (withdrawn) counts.wrongWithdrawn += 1; else counts.wrongNotWithdrawn += 1;
  const selectedBus = session.buses.find((bus) => bus.id === run.selected!.vehicleId)!;
  const boardedShown = firstShownReaching(session, boarded, run.selected.at);
  const selectedShown = firstShownReaching(session, selectedBus, run.selected.at);
  if (boardedShown !== undefined && (selectedShown === undefined || boardedShown <= selectedShown)) {
    counts.shownOvertaken += 1;
    if (!withdrawn || run.withdrawnAt! > boardedShown) counts.shownOvertakenNotWithdrawn += 1;
  }
}

const summary = {
  schemaVersion: 1,
  evidenceClass: "SIMULATED",
  countsAsLiveEvidence: false,
  matcherPolicy: MATCHER_POLICY_VERSION,
  generator: "services/api/test/groundTruthKit.ts",
  model: "buses at a steady 20-90 s per stop, visible late, in holes and with per-poll dropout; 10 s polls, 2 % failed; the rider waits from the first poll and boards the first bus to reach the stop",
  seeds: { first: 1, last: sessions },
  counts,
};

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, `${JSON.stringify(summary, null, 2)}\n`);
console.log(JSON.stringify(counts));
