/**
 * Render the instant-level re-decision of every former wrong commit as a
 * human-readable table, from the machine-readable artifact alone.
 *
 *   node --experimental-strip-types scripts/matcher-evidence/render-instants.ts \
 *     [--in=artifacts/matcher-directed-v1/former-wrong-commit-instants.json] \
 *     [--out=docs/validation/FORMER_WRONG_COMMITS_UNDER_DIRECTED_POLICY.md]
 *
 * Deterministic: the same artifact always renders the same document, and CI
 * can regenerate it to check the two have not drifted.
 */

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const options = new Map(process.argv.slice(2).map((arg) => {
  const [key, ...value] = arg.replace(/^--/, "").split("=");
  return [key!, value.join("=")];
}));
const inPath = path.resolve(options.get("in") || "artifacts/matcher-directed-v1/former-wrong-commit-instants.json");
const outPath = path.resolve(options.get("out") || "docs/validation/FORMER_WRONG_COMMITS_UNDER_DIRECTED_POLICY.md");

interface Row {
  caseId: string;
  routeId: string;
  boardingSequence: number;
  commitAt: string;
  formerMechanism: string;
  formerCommittedStopOffset: number;
  legacyReproduced: boolean;
  current: {
    status: string;
    selectedRole?: string;
    abstentionReasons: string[];
    formerSelectionZone: string;
    trueBusZone?: string;
    formerSelectionRejectedBecause: string[];
  };
}

const bytes = await readFile(inPath);
const artifact = JSON.parse(bytes.toString("utf8")) as {
  matcherPolicy: string;
  controlPolicy: string;
  source: { ledgerSha256: string };
  totals: Record<string, unknown>;
  records: Row[];
};
const sha = createHash("sha256").update(bytes).digest("hex");

const byRoute = new Map<string, Row[]>();
for (const row of artifact.records) {
  const list = byRoute.get(row.routeId) ?? [];
  list.push(row);
  byRoute.set(row.routeId, list);
}

const mechanism = (value: string) => (value.includes("NOT_IN_FEED") ? "M2" : value.includes("BEYOND") ? "M1" : value);
const lines: string[] = [];
lines.push("# Former live wrong commits under the directed matcher");
lines.push("");
lines.push(`Generated by \`scripts/matcher-evidence/render-instants.ts\` from \`artifacts/matcher-directed-v1/former-wrong-commit-instants.json\` (sha256 \`${sha}\`), which re-decides each of the 268 wrong commits in the Passive Shadow v3 evidence-of-record ledger (sha256 \`${artifact.source.ledgerSha256}\`) at the instant it was made. Policy under test \`${artifact.matcherPolicy}\`; control \`${artifact.controlPolicy}\`. Pseudonymous; \`LIVE_PASSIVE\` base, \`VERIFIED_BY_REPLAY\` at instant level.`);
lines.push("");
lines.push("**What this establishes.** At each former wrong commit's decision instant, with every candidate the ledger recorded (stop sequence, cadence state), the legacy policy reproduces the recorded selection and the directed policy makes no selection at all. Topology is assumed permissively (a straight route, no repeated stop) and memory of absent vehicles is empty; the real inputs can only add abstentions.");
lines.push("");
lines.push("**What it does not establish.** What the directed policy does later in each case's window, when the true bus approaches. That needs the raw streams and `scripts/passive-shadow/migrate.ts`; see `docs/exec-plans/HUMAN_LABOR_ELIMINATION.md` §8.");
lines.push("");
lines.push("## Totals");
lines.push("");
lines.push("| Measure | Value |");
lines.push("|---|---|");
for (const [key, value] of Object.entries(artifact.totals)) lines.push(`| ${key} | ${typeof value === "object" ? `\`${JSON.stringify(value)}\`` : String(value)} |`);
lines.push("");
lines.push("Legend: S = boarding stop sequence. Former offset = stops past S of the bus the legacy matcher committed to. M1 = true bus in the feed but 5–14 stops back; M2 = true bus absent from that snapshot. Now = the directed policy's status at the same instant, with its withholding reasons and why the former pick is refused.");
lines.push("");
for (const [routeId, rows] of [...byRoute].sort(([left], [right]) => left.localeCompare(right))) {
  lines.push(`## Route \`${routeId}\`: ${rows.length} former wrong commits`);
  lines.push("");
  lines.push("| # | Commit instant (UTC) | S | Former offset | Mech. | Legacy reproduced | Now | Former pick refused as | True bus now | Withholding reasons |");
  lines.push("|---:|---|---:|---:|---|---|---|---|---|---|");
  rows.forEach((row, index) => {
    lines.push(`| ${index + 1} | ${row.commitAt.slice(11, 19)} | ${row.boardingSequence} | +${row.formerCommittedStopOffset} | ${mechanism(row.formerMechanism)} | ${row.legacyReproduced ? "yes" : "**no**"} | ${row.current.status}${row.current.selectedRole ? ` → ${row.current.selectedRole}` : ""} | ${row.current.formerSelectionZone} (${row.current.formerSelectionRejectedBecause.join(", ")}) | ${row.current.trueBusZone ?? "absent from feed"} | ${row.current.abstentionReasons.join(", ") || "—"} |`);
  });
  lines.push("");
}
await writeFile(outPath, `${lines.join("\n")}\n`);
console.log(`${path.relative(process.cwd(), outPath)}: ${artifact.records.length} rows`);
