// GENERATED by scripts/crosswalk/jeju-stop-crosswalk.ts. Do not edit.
// VERIFIED_EXACT rows only (docs/validation/JEJU_BIS_TAGO_STOP_CROSSWALK.md).
// Empty: no official evidence has been classified yet, so no stop has a station id.

extension JejuStopCrosswalk {
    public static let shipped = JejuStopCrosswalk(
        catalogVersion: "794f3bcb831d783e",
        generatedAt: "none",
        entries: []
    )
}
