#!/usr/bin/env python3
"""Turn the timetable census into what the runtime serves, and a review report.

    python3 scripts/timetables/build_bundle.py [--previous OLD_MANIFEST.json]

Reads `fixtures/jeju/timetables/bis/` (the manifest and each parsed dataset)
and writes:

    services/api/data/jeju-timetables.json   every dataset whose status is
        `parsed` or `source_conflict`, compact, with the census counts. The API
        serves only services whose own status is `ok`.
    artifacts/timetables/jeju-timetable-census.md   counts, every refusal and
        conflict, and, with --previous, what changed since that manifest:
        added and removed timetables, changed files, effective-date and
        first/last-bus changes, new parse outcomes.

Deterministic: the same inputs give the same bytes. Standard library only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CENSUS = ROOT / "fixtures/jeju/timetables/bis"
BUNDLE = ROOT / "services/api/data/jeju-timetables.json"
REPORT = ROOT / "artifacts/timetables/jeju-timetable-census.md"
BUNDLE_SCHEMA = "tapso-jeju-timetable-bundle-v1"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def first_last(dataset: dict) -> dict[str, tuple[str | None, str | None]]:
    """(direction|dayType|route) -> (first row start, last row start), for change reports."""
    out = {}
    for service in dataset.get("services", []):
        for route in service.get("routeNumbers", []):
            starts = [trip.get("firstTime") for trip in service["trips"] if trip.get("routeNumber") == route and trip.get("firstTime")]
            out[f"{route} | {service['direction']} | {service['dayType']}"] = (starts[0] if starts else None, starts[-1] if starts else None)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--previous", type=Path, help="an older manifest.json to report changes against")
    args = parser.parse_args()

    manifest = load(CENSUS / "manifest.json")
    datasets = []
    for record in manifest["timetables"]:
        if record["outcome"] in ("parsed", "source_conflict"):
            dataset = load(CENSUS / f"{record['id']}.json")
            if dataset["source"]["sha256"] != record["sha256"]:
                raise SystemExit(f"{record['id']}: dataset checksum differs from the manifest")
            datasets.append(dataset)
    datasets.sort(key=lambda dataset: dataset["source"]["scheduleId"])
    body = {"datasets": datasets}
    version = hashlib.sha256(json.dumps(body, ensure_ascii=False, sort_keys=True).encode()).hexdigest()[:16]
    bundle = {
        "schemaVersion": BUNDLE_SCHEMA,
        "label": "OFFICIAL_DATED",
        "bundleVersion": version,
        "source": {"page": manifest["source"], "dataset": manifest["dataset"]},
        "retrievedOn": manifest["retrievedOn"],
        "retrievedAt": manifest["retrievedAt"],
        "parser": manifest["parser"],
        "census": {
            "entries": len(manifest["timetables"]),
            "counts": manifest["counts"],
            "noTimetable": [
                {"scheduleId": record["id"], "name": record["name"], "reason": record.get("reason", "site_has_none")}
                for record in manifest["timetables"] if record["outcome"] == "no_timetable"
            ],
            "refused": [
                {"scheduleId": record["id"], "name": record["name"], "family": record.get("family"), "reason": record.get("reason")}
                for record in manifest["timetables"] if record["outcome"] == "parse_refused"
            ],
        },
        **body,
    }
    BUNDLE.parent.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_text(json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")

    lines = [
        "# Jeju timetable census",
        "",
        f"Source: {manifest['source']} ({manifest['dataset']}), downloaded {manifest['retrievedAt']}. "
        f"Parser {manifest['parser']['name']} v{manifest['parser']['version']}. Bundle `{version}`.",
        "",
        "Generated by `scripts/timetables/build_bundle.py`; do not edit by hand. Official, dated: never live.",
        "",
        "| Outcome | Timetables |",
        "|---|---|",
        *[f"| {outcome} | {count} |" for outcome, count in sorted(manifest["counts"].items())],
        f"| **total** | **{len(manifest['timetables'])}** |",
        "",
    ]
    services = [service for dataset in datasets for service in dataset["services"]]
    by_day: dict[str, int] = {}
    for service in services:
        by_day[service["dayType"]] = by_day.get(service["dayType"], 0) + 1
    lines += [
        f"Services (one per direction and day type): {len(services)}, of which "
        f"{sum(1 for service in services if service['status'] == 'ok')} are served and "
        f"{sum(1 for service in services if service['status'] != 'ok')} are withheld as source conflicts.",
        "",
        "| Day type | Services |",
        "|---|---|",
        *[f"| {day} | {count} |" for day, count in sorted(by_day.items())],
        "",
        "## Source conflicts (kept, never served)",
        "",
    ]
    for record in manifest["timetables"]:
        if record["outcome"] == "source_conflict":
            lines.append(f"- **{record['name']}** (`{record['id']}`): " + "; ".join(record.get("conflicts", [])))
    lines += ["", "## No timetable", ""]
    for record in manifest["timetables"]:
        if record["outcome"] == "no_timetable":
            lines.append(f"- **{record['name']}** (`{record['id']}`): {record.get('reason', 'the site lists the route but has no timetable for it')}")
    lines += ["", "## Refused (outside the parser's grammar)", ""]
    refused = [record for record in manifest["timetables"] if record["outcome"] == "parse_refused"]
    lines += [f"- **{record['name']}** (`{record['id']}`), family `{record.get('family')}`: {record.get('reason')}" for record in refused] or ["None."]

    if args.previous:
        old = load(args.previous)
        old_by_id = {record["id"]: record for record in old["timetables"]}
        new_by_id = {record["id"]: record for record in manifest["timetables"]}
        lines += ["", f"## Changes since {old.get('retrievedAt', args.previous.name)}", ""]
        added = sorted(set(new_by_id) - set(old_by_id))
        removed = sorted(set(old_by_id) - set(new_by_id))
        added_names = ", ".join(f"{new_by_id[i]['name']} (`{i}`)" for i in added) or "none"
        removed_names = ", ".join(f"{old_by_id[i]['name']} (`{i}`)" for i in removed) or "none"
        lines.append(f"- Added: {added_names}")
        lines.append(f"- Removed: {removed_names}")
        for identifier in sorted(set(new_by_id) & set(old_by_id)):
            before, after = old_by_id[identifier], new_by_id[identifier]
            notes = []
            if before.get("sha256") != after.get("sha256"):
                notes.append("file changed")
            if before.get("outcome") != after.get("outcome"):
                notes.append(f"outcome {before.get('outcome')} → {after.get('outcome')}")
            old_path = args.previous.parent / f"{identifier}.json"
            if after["outcome"] in ("parsed", "source_conflict") and old_path.exists():
                old_dataset, new_dataset = load(old_path), load(CENSUS / f"{identifier}.json")
                old_dates = sorted({s.get("effectiveFrom") for s in old_dataset.get("services", []) if s.get("effectiveFrom")})
                new_dates = sorted({s.get("effectiveFrom") for s in new_dataset.get("services", []) if s.get("effectiveFrom")})
                if old_dates != new_dates:
                    notes.append(f"시행일 {old_dates} → {new_dates}")
                old_fl, new_fl = first_last(old_dataset), first_last(new_dataset)
                for key in sorted(set(old_fl) | set(new_fl)):
                    if old_fl.get(key) != new_fl.get(key):
                        notes.append(f"first/last {key}: {old_fl.get(key)} → {new_fl.get(key)}")
            if notes:
                lines.append(f"- {after['name']} (`{identifier}`): " + "; ".join(notes))
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"bundleVersion": version, "datasets": len(datasets), "services": len(services), "counts": manifest["counts"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
