/**
 * Which kind of day a Korean calendar date is, and whether a timetable's day
 * type applies to it.
 *
 * Holidays come from `data/kr-public-holidays.json`, generated by
 * `scripts/calendar/generate_kr_holidays.py` (관공서의 공휴일 including
 * substitute holidays and election days; sources and generator version are in
 * the file). Outside the file's `validFrom`…`validThrough` the holiday status of
 * a date is unknown, and every answer that depends on it says `uncertain`.
 *
 * Rules, each from the timetable's own day label (scripts/timetables/jeju_xlsx.py):
 * - weekday ("평일"): Monday–Friday that is not a public holiday.
 * - saturday ("토요일"): a Saturday that is not a public holiday; a Saturday
 *   holiday takes the holiday timetable where the route publishes one.
 * - sunday_holiday ("일,공휴일"): Sundays and public holidays.
 * - saturday_sunday_holiday ("토,공휴일", "주말/공휴일"): Saturdays, Sundays and
 *   public holidays. Sunday is a public holiday under 관공서의 공휴일에 관한 규정
 *   제2조 제1호.
 * - holiday_saturday_unstated ("휴일"): Sundays and public holidays apply;
 *   whether an ordinary Saturday does is not stated, so it is `uncertain`.
 * - unstated (no day label): never claimed for any date; `unstated`.
 */

export type Weekday = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
export type DayTypeApplicability = "applies" | "does_not_apply" | "uncertain" | "unstated";

export interface HolidayCalendar {
  schemaVersion: "tapso-kr-public-holidays-v1";
  validFrom: string;
  validThrough: string;
  generator: { library: string; version: string; category: string };
  sources: string[];
  holidays: { date: string; name: string; source?: string }[];
}

export interface ServiceDay {
  /** `YYYY-MM-DD`, a date in Korea. */
  date: string;
  weekday: Weekday;
  /** The public holiday on this date, `null` when there is none, `undefined` when the calendar does not cover it. */
  publicHoliday: { name: string } | null | undefined;
  calendarCovered: boolean;
}

const WEEKDAYS: Weekday[] = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
const DATE = /^(\d{4})-(\d{2})-(\d{2})$/;

export class HolidayCalendarError extends Error {
  readonly code = "HOLIDAY_CALENDAR_INVALID";
}

export function validateHolidayCalendar(raw: unknown): HolidayCalendar {
  const calendar = raw as HolidayCalendar;
  if (!calendar || calendar.schemaVersion !== "tapso-kr-public-holidays-v1") throw new HolidayCalendarError("unsupported holiday calendar");
  if (!isDate(calendar.validFrom) || !isDate(calendar.validThrough) || calendar.validFrom > calendar.validThrough) {
    throw new HolidayCalendarError("validFrom/validThrough are not an ordered pair of dates");
  }
  if (!Array.isArray(calendar.holidays)) throw new HolidayCalendarError("holidays must be a list");
  const seen = new Set<string>();
  for (const entry of calendar.holidays) {
    if (!isDate(entry.date) || entry.date < calendar.validFrom || entry.date > calendar.validThrough) {
      throw new HolidayCalendarError(`holiday ${String(entry.date)} is not a date inside the calendar's range`);
    }
    if (typeof entry.name !== "string" || !entry.name) throw new HolidayCalendarError(`holiday ${entry.date} has no name`);
    if (seen.has(entry.date)) throw new HolidayCalendarError(`holiday ${entry.date} appears twice`);
    seen.add(entry.date);
  }
  return calendar;
}

/** Today's date in Korea (UTC+9 all year; Korea has no daylight saving time). */
export function koreanDate(now: Date): string {
  return new Date(now.getTime() + 9 * 3_600_000).toISOString().slice(0, 10);
}

export function serviceDay(date: string, calendar: HolidayCalendar): ServiceDay {
  if (!isDate(date)) throw new RangeError(`not a date: ${date}`);
  const [, year, month, day] = DATE.exec(date)!;
  const weekday = WEEKDAYS[new Date(Date.UTC(Number(year), Number(month) - 1, Number(day))).getUTCDay()]!;
  const covered = date >= calendar.validFrom && date <= calendar.validThrough;
  const holiday = calendar.holidays.find((entry) => entry.date === date);
  return {
    date,
    weekday,
    publicHoliday: covered ? (holiday ? { name: holiday.name } : null) : undefined,
    calendarCovered: covered,
  };
}

export function dayTypeApplies(dayType: string, day: ServiceDay): DayTypeApplicability {
  const holiday = day.publicHoliday;
  const known = holiday !== undefined;
  const isHoliday = holiday !== null && holiday !== undefined;
  const weekend = day.weekday === "sat" || day.weekday === "sun";
  switch (dayType) {
    case "weekday":
      if (weekend) return "does_not_apply";
      return known ? (isHoliday ? "does_not_apply" : "applies") : "uncertain";
    case "saturday":
      if (day.weekday !== "sat") return "does_not_apply";
      return known ? (isHoliday ? "does_not_apply" : "applies") : "uncertain";
    case "sunday_holiday":
      if (day.weekday === "sun") return "applies";
      return known ? (isHoliday ? "applies" : "does_not_apply") : "uncertain";
    case "saturday_sunday_holiday":
      if (weekend) return "applies";
      return known ? (isHoliday ? "applies" : "does_not_apply") : "uncertain";
    case "holiday_saturday_unstated":
      if (day.weekday === "sun") return "applies";
      if (known && isHoliday) return "applies";
      if (day.weekday === "sat") return "uncertain";
      return known ? "does_not_apply" : "uncertain";
    case "unstated":
      return "unstated";
    default:
      // A day type this code has not read is never applied.
      return "uncertain";
  }
}

function isDate(value: unknown): value is string {
  if (typeof value !== "string") return false;
  const match = DATE.exec(value);
  if (!match) return false;
  const [, year, month, day] = match;
  const parsed = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day)));
  return parsed.getUTCFullYear() === Number(year) && parsed.getUTCMonth() === Number(month) - 1 && parsed.getUTCDate() === Number(day);
}
